version: '2'
services:

  movie-app:
    image: movieapp
    build:
      context: ./
      dockerfile: Dockerfile
      network_mode: host
      restart: always
      ports:
      - 4200:4200
      entrypoint: ./index.js
      - '0.0.0.0'
      - '4200'